### ISSUE TITLE
release der letzten Version

### ISSUE THREAD

**Issue by sejoharp** [deflomu/moneymoney-mintos-extension#1]
Moin, kannst Du die letzte Version signieren lassen, damit sie ohne MoneyMoney Beta funktioniert.

Ich hatte das Problem, dass ich nicht alle Investionen angezeigt wurden. Mit der letzten Version funktioniert das einwandfrei. 

vielen Dank.

**Comment by deflomu** [comment]
Ja mach ich

**Comment by deflomu** [comment]
Die neue Version ist signiert und kann hier: https://moneymoney-app.com/extensions/ runtergeladen werden.
