### ISSUE TITLE
"Das Passwort wurde vom Server als ungültig abgewiesen."

### ISSUE THREAD

**Issue by lenikey** [deflomu/moneymoney-mintos-extension#12]
Since a few days ago I can't login via the extension anymore. This might correlate with the new Mintos website also being online for a few days now.

**Comment by lr1980** [comment]
ich hab ein pull request dazu erstellt => #13

**Comment by blue-dog1** [comment]
Bei mir kommt mit der neuen LUA folgende Meldung:
Mintos.lua:150: attempt to index field 'data' (a nil value)

**Comment by deflomu** [comment]
@blue-dog1 Könntest du mal die aktuelle master-Version testen? Ich hab dort einen Fix für den Fehler eingebaut. Du hast vermutlich 2-Faktor-Auth aktiviert?

**Comment by deflomu** [comment]
@blue-dog1 Die neue Version ist nicht im master, sondern hier: https://github.com/deflomu/moneymoney-mintos-extension/blob/issue-11-2fa/Mintos.lua

**Comment by blue-dog1** [comment]
Sorry für die späte Antwort...
Läuft jetzt. Die 2FA hatte ich nicht aktiviert... Die geht ja noch nicht ;)
Vielen Dank für's schnelle fixen!

**Comment by deflomu** [comment]
Kannst du 2fa auch mal probieren? Das sollte hoffentlich jetzt auch gehen

**Comment by blue-dog1** [comment]
Da bekomm ich jetzt wieder den hier (bei V1.7)
Mintos.lua:150: attempt to index field 'data' (a nil value)
Kann aber leider keine Betas testen, weil ich moneymoney im AppStore gekauft habe. 


Am 12.08.19 um 12:58 schrieb Florian Mutter

Kannst du 2fa auch mal probieren? Das sollte hoffentlich jetzt auch gehen

**Comment by deflomu** [comment]
Ich hab eine neue Version veröffentlicht: https://github.com/deflomu/moneymoney-mintos-extension/releases/tag/v1.8

**Comment by lenikey** [comment]
Der Fehler erscheint erneut bei mir.
