### ISSUE TITLE
Signatur

### ISSUE THREAD

**Issue by ghost** [deflomu/moneymoney-mintos-extension#4]
Hallo,
Erstmal danke für die Extension. =))
Leider bekomme ich für eines der zwei Konten auf Mintos nur 0€ angezeigt. Woran kann das liegen?

Lieben Dank!

**Comment by tkajen** [comment]
Hallo,
ja bei mir ist auch so. Die investierte Kredite werden anscheinend nicht angezeigt. Kann man da was machen?

Grüße

**Comment by lr1980** [comment]
mein pull request könnte helfen: #5 
damit funktioniert bei mir die "Invested Funds" wieder...

**Comment by deflomu** [comment]
Sollte mit Version 1.6 besser funktionieren. Es kann ein paar Tage dauern bis diese auf moneymoney-app.de verfügbar ist.
