### ISSUE TITLE
Invested Funds inkorrekt

### ISSUE THREAD

**Issue by Spottycat** [deflomu/moneymoney-mintos-extension#6]
Hallo,

vielen Dank für die Extension ^-^

Bei mir ist es aktuell so, dass "Available Funds" korrekt angezeigt wird, "Invested Funds" hängt aber irgendwie fix bei einem Betrag fest, obwohl ich zwischenzeitlich Einzahlungen vorgenommen und neue Investment getätigt habe. 

Keine Fehler bei der Aktualisierung.

Kann es sein, dass nur 100 items verarbeitet werden?
"Received 100 portfolio items, 0 are new."

Ich habe doch ein paar mehr Portfolio items, was den Unterschied im Betrag erklären würde.

Vielen Dank im Voraus
und Gruß

**Comment by Smabian** [comment]
Hallo, 

Bei mir sind es auch nur 100 Investments die angezeigt werden.

So wie es aussieht liest der Mintos Request 100 Einträge pro Seite aus:

```
"https://www.mintos.com/en/my-investments/list", 
"currency=978&+=978&with_buyback=&statuses%5B%5D=256&statuses%5B%5D=512&statuses%5B%5D=1024&statuses%5B%5D=2048&statuses%5B%5D=8192&statuses%5B%5D=16384&purchased_from=&purchased_till=&listed_for_sale_status=&min_interest=&max_interest=&min_term=&max_term=&min_ltv=&max_ltv=&loan_id=&sort_field=&sort_order=DESC&max_results=**100**&page=" .. 
```

Ich vermute das die zweite Seite der Einträge nie ausgelesen wird da `while page < total do` (Zeile 111) immer nur die Seite ausliest so lange page kleiner total ist. Wenn wir auf der letzten Seite sind ist die aktuelle Seite (page) gleich der letzten Seite (total)

```
total = list["data"]["result"]["totalPages"]
page = list["data"]["result"]["pagination"]["currentPage"] + 1
```

Man müsste daher denke ich entweder den Request anpassen oder die Schleife auf <= ändern. Ich kann die Änderungen bei mir aber leider nicht testen und weiß daher nicht ob es das Problem beheben wird. 

Vielen Dank und viele Grüße

**Comment by zafai** [comment]
Ich habe gerade einen Pull request gestellt https://github.com/deflomu/moneymoney-mintos-extension/pull/7
In dem hab ich den Request angepasst und die Schleife geändert damit funktioniert es bei mir.

**Comment by deflomu** [comment]
Sollte mir der aktuellen Version richtig funktionieren. Danke für den Pull Request
